version: "3.8"
services:
 

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: localhost
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: dsjsdggshdgbjdsvh

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data


volumes:
  redis:
    driver: local
